### ISSUE TITLE
is this supposed to work?

### ISSUE THREAD

**Issue by ricardoalcocer** [queueit/KnownUser.V3.Cloudflare#7]
Hi.

The readme makes reference to copying over the contents from a file (queueitknownuser.bundle.js) that was deleted on Nov 29, 2021 by this commit https://github.com/queueit/KnownUser.V3.Cloudflare/commit/6e7cb99e002ace4080c9e3f5120b132bd1b38084

Shall I assume that this is not supposed to work at all?

**Comment by ricardoalcocer** [comment]
7 days and no response? 

I'm assuming this is **NOT** supposed to work.

**Comment by frwiqueueit** [comment]
Hi,
The readme mentions the bundle is found under releases. It can be found under Assets.
https://github.com/queueit/KnownUser.V3.Cloudflare/releases

**Comment by frwiqueueit** [comment]
I will update the readme to make it stand out more. Thanks.

**Comment by sarooghi** [comment]
If you need more help and faster response please contact support@queue-it.com our support team  will help you install the worker.
